spring.application.name=interview-prep

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/interviewprep}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:interviewprep}

server.port=${PORT:8082}

jwt.secret=${JWT_SECRET:interviewPrepSecretKey2024XYZ123456789abcdef}
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:pugalabishek1042006@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:okvymwydwwgsbxbd}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
