spring.application.name=interview-prep
spring.data.mongodb.uri=mongodb://localhost:27017/interviewprep
spring.data.mongodb.database=interviewprep
# Use 8082 for Maven development, 8081 for jar/production
server.port=8082
jwt.secret=interviewPrepSecretKey2024XYZ123456789abcdef
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pugalabishek1042006@gmail.com
spring.mail.password=okvymwydwwgsbxbd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true